// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4fXwzLsFeUSR2Reme3C89G7zQyB0WfuI',
    appId: '1:368179434888:android:01be0e975516607cd4163d',
    messagingSenderId: '368179434888',
    projectId: 'flutter-chat-app-c4924',
    storageBucket: 'flutter-chat-app-c4924.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_93AlxYmLcXEKI3mJqgtpvN0fj2JDgJQ',
    appId: '1:368179434888:ios:944e0b0d4f0fe1cad4163d',
    messagingSenderId: '368179434888',
    projectId: 'flutter-chat-app-c4924',
    storageBucket: 'flutter-chat-app-c4924.appspot.com',
    iosBundleId: 'com.example.pg2App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_93AlxYmLcXEKI3mJqgtpvN0fj2JDgJQ',
    appId: '1:368179434888:ios:944e0b0d4f0fe1cad4163d',
    messagingSenderId: '368179434888',
    projectId: 'flutter-chat-app-c4924',
    storageBucket: 'flutter-chat-app-c4924.appspot.com',
    iosBundleId: 'com.example.pg2App',
  );
}
